### PR TITLE
Added "data.table"

### PR DESCRIPTION
**Pull request by shahryary**
Using "data.table" instead of "utils::read.table", it's managing so fast to read/write the files.

### CODE REVIEW

**Comment by ataudt** [comment]
Hi, thanks for the hint. Is it possible to use data.table::fread("file.gz") on gz files similar to utils::read.table("file.gz")?

**Comment by shahryary** [comment]
Yes, you can use it. for instance: 
data <- fread("gunzip -c methylome_7413_merged_CXreport.txt.gz")

**Comment by ataudt** [comment]
That assumes gunzip is present on the system, which I cannot do in a package. Any other way? Otherwise I will put the fread in a tryCatch block, and fall back to read.table in case of error.

**Comment by shahryary** [comment]
Well, it's better to use in tryCatch because there is no other way( at this moment) to read the gzip files.

**Pull request merged**
